// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjGSO8fpyhWzM5J2KApcyZeEzD9YVZJc',
    appId: '1:545698172331:web:695662d82bfd9584b116ee',
    messagingSenderId: '545698172331',
    projectId: 'fireabseailogic',
    authDomain: 'fireabseailogic.firebaseapp.com',
    storageBucket: 'fireabseailogic.firebasestorage.app',
    measurementId: 'G-31GGXSQEL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDji93EMThXoj1alsRLL-6z-LC-C0cBlDc',
    appId: '1:545698172331:android:1f5be47226948340b116ee',
    messagingSenderId: '545698172331',
    projectId: 'fireabseailogic',
    storageBucket: 'fireabseailogic.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFjGSO8fpyhWzM5J2KApcyZeEzD9YVZJc',
    appId: '1:545698172331:web:580f5c6a9df8c05bb116ee',
    messagingSenderId: '545698172331',
    projectId: 'fireabseailogic',
    authDomain: 'fireabseailogic.firebaseapp.com',
    storageBucket: 'fireabseailogic.firebasestorage.app',
    measurementId: 'G-QYQV0528CP',
  );
}
